### ISSUE TITLE
Spa Booking App - Final Capstone project

### ISSUE THREAD

**Issue by Jeddaa** [newhoteng/spa-booking-backend#17]
Dear reviewer,

- This is a group of 4 and we are going to use this kanban board to achieve our milestone towards the completion of this project.
- https://github.com/users/newhoteng/projects/10

<img width="1428" alt="Screenshot 2023-08-16 at 11 44 47" src="https://github.com/newhoteng/spa-booking-backend/assets/88030896/f91090de-4941-489d-b5b5-518b45505aa0">
<img width="1428" alt="Screenshot 2023-08-16 at 11 45 02" src="https://github.com/newhoteng/spa-booking-backend/assets/88030896/c8e8c5ee-1046-45aa-b576-17731fa99d92">
<img width="1428" alt="Screenshot 2023-08-16 at 11 45 10" src="https://github.com/newhoteng/spa-booking-backend/assets/88030896/11946452-326a-4b4e-8433-47ff1f7f8945">

**Comment by Meltrust** [comment]
Hi @Jeddaa,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, have descriptions and pointings.  The pointings are equal according to the requirement. ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
